const WORDS = {
    bollywood: [
        ["Sholay", "Deewar"],
        ["DDLJ", "Kuch Kuch Hota Hai"],
        ["3 Idiots", "PK"],
        ["Lagaan", "Chak De India"],
        ["Gangs of Wasseypur", "Mirzapur"],
        ["Andaz Apna Apna", "Hera Pheri"],
        ["Gully Boy", "Zindagi Na Milegi Dobara"],
        ["Dangal", "Sultan"],
        ["Bahubali", "RRR"],
        ["Padmaavat", "Bajirao Mastani"],
        ["Jab We Met", "Love Aaj Kal"],
        ["Dil Chahta Hai", "Zindagi Na Milegi Dobara"],
        ["Munna Bhai MBBS", "Lage Raho Munna Bhai"],
        ["Kabhi Khushi Kabhie Gham", "Kal Ho Naa Ho"],
        ["Om Shanti Om", "Ra.One"],
        ["Pushpa", "KGF"],
        ["Stree", "Bhediya"],
        ["Rang De Basanti", "Yuva"],
        ["Queen", "English Vinglish"],
        ["Barfi", "PK"],
        ["Taare Zameen Par", "Like Stars on Earth"],
        ["Bajrangi Bhaijaan", "Tubelight"],
        ["Raees", "Don"],
        ["Dhoom", "Race"],
        ["Dabangg", "Singham"],
        ["Golmaal", "Dhamaal"],
        ["Welcome", "No Entry"],
        ["Dilwale", "Chennai Express"],
        ["Rockstar", "Tamasha"],
        ["Aashiqui 2", "Ek Villain"],
        ["Udaan", "Masaan"],
        ["Gangs of Wasseypur 2", "Ugly"],
        ["Agneepath", "Kaante"],
        ["Kai Po Che", "Rock On"],
        ["Haider", "Omkara"],
        ["Black Friday", "Special 26"],
        ["Dhoom 3", "Bang Bang"],
        ["Neerja", "Baby"],
        ["Kahaani", "Talaash"],
        ["Badhaai Ho", "Shubh Mangal Zyada Saavdhan"],
        ["Toilet Ek Prem Katha", "Pad Man"],
        ["Sanju", "Bhopal A Prayer for Rain"],
        ["Uri", "Shershaah"],
        ["Article 15", "Mulk"],
        ["Tumbbad", "Rahi"],
        ["Drishyam", "Badla"],
        ["Chhichhore", "Super 30"],
        ["War", "Tiger Zinda Hai"],
        ["Pathaan", "Jawan"],
        ["Animal", "Kabir Singh"],
    ],
    memes: [
        ["Binod", "Normie"],
        ["Rasode Mein Kaun Tha", "Taarak Mehta"],
        ["Pawri Ho Rahi Hai", "Chai Peelo"],
        ["Chup Bilkul Chup", "Thappad Se Darr Nahi Lagta"],
        ["Hera Pheri Templates", "Baburao"],
        ["Coffin Dance", "Rickroll"],
        ["Woman Yelling at Cat", "Distracted Boyfriend"],
        ["Drake Hotline Bling", "Two Buttons"],
        ["Stonks", "This is Fine"],
        ["Sigma Male", "Chad"],
        ["Ek Baar Jo Maine Commitment Kar Di", "Crime Master Gogo"],
        ["Dank Memes", "Normie Memes"],
        ["Amitabh Stare", "Jethalal Face"],
        ["Wah Kya Scene Hai", "Arey Yaar"],
        ["Triggered Insaan", "Carry Minati"],
        ["Dogecoin", "Pepe the Frog"],
        ["Sasta Drake", "Indian Meme Templates"],
        ["Bernie Sanders Mittens", "Obama Medal"],
        ["Surprised Pikachu", "Blinking Guy"],
        ["Expanding Brain", "Galaxy Brain"],
        ["Hide the Pain Harold", "Bad Luck Brian"],
        ["Roll Safe Think About It", "Change My Mind"],
        ["One Does Not Simply", "Brace Yourselves"],
        ["Success Kid", "Disaster Girl"],
        ["Shut Up and Take My Money", "Panik Kalm Panik"],
        ["Tum karo toh chamatkar", "Main karun toh paap"],
        ["Ye bik gayi hai gormint", "Bohot hard"],
        ["Rahul Gandhi Pappu", "Modi Memes"],
        ["Carryminati Yalgaar", "Amir Siddiqui"],
        ["Tanmay Bhat Roast", "AIB"],
        ["Hindustani Bhau", "Lakshay Chaudhary"],
        ["Elvish Yadav vs Maxtern", "Round2Hell"],
        ["I am once again asking", "Pointing Rick Dalton"],
        ["Always has been", "Wait it's all Ohio"],
        ["Starter Pack", "Nobody Absolutely Nobody"],
        ["Me explaining to my mom", "Mom can we have"],
        ["Corporate needs you to find", "Spider-Man Pointing"],
        ["Friendship ended with", "Amul Topical"],
        ["Area 51 Raid", "Tide Pod Challenge"],
        ["Ice Bucket Challenge", "Mannequin Challenge"],
        ["Harshad Mehta Scam Template", "Jethalal No No"],
        ["Disappointed Cricket Fan", "Pakistani Fan Meme"],
        ["Manoj Bajpayee Family Man", "Pankaj Tripathi Mirzapur"],
        ["Cat Vibing", "Dog Side Eye"],
        ["Shaq Sleeping", "Megamind No B*tches"],
        ["NPC Meme", "Soyboy"],
        ["Skeletor Disturbing Facts", "Peter Griffin Skin Color"],
        ["Gym Bros", "Ligma"],
        ["That's What She Said", "Deez Nuts"],
        ["Sus Amogus", "Backrooms"],
    ],
    celebrities: [
        ["Shah Rukh Khan", "Aamir Khan"],
        ["Ranveer Singh", "Ranbir Kapoor"],
        ["Deepika Padukone", "Priyanka Chopra"],
        ["Amitabh Bachchan", "Rajinikanth"],
        ["Virat Kohli", "MS Dhoni"],
        ["Salman Khan", "Akshay Kumar"],
        ["Alia Bhatt", "Ananya Panday"],
        ["Hrithik Roshan", "Tiger Shroff"],
        ["Kareena Kapoor", "Katrina Kaif"],
        ["CarryMinati", "Tanmay Bhat"],
        ["Nawazuddin Siddiqui", "Pankaj Tripathi"],
        ["Nora Fatehi", "Disha Patani"],
        ["AR Rahman", "Arijit Singh"],
        ["Sachin Tendulkar", "Sourav Ganguly"],
        ["Kapil Sharma", "Bharti Singh"],
        ["Shreya Ghoshal", "Neha Kakkar"],
        ["Rajkummar Rao", "Ayushmann Khurrana"],
        ["Madhuri Dixit", "Sridevi"],
        ["Varun Dhawan", "Sidharth Malhotra"],
        ["Tabu", "Vidya Balan"],
        ["Kartik Aaryan", "Vicky Kaushal"],
        ["Kiara Advani", "Janhvi Kapoor"],
        ["Sunny Deol", "Ajay Devgn"],
        ["Govinda", "David Dhawan"],
        ["Anil Kapoor", "Jackie Shroff"],
        ["Shah Rukh Khan", "Hrithik Roshan"],
        ["Rohit Sharma", "KL Rahul"],
        ["Hardik Pandya", "Ravindra Jadeja"],
        ["Sania Mirza", "PV Sindhu"],
        ["Neeraj Chopra", "Abhinav Bindra"],
        ["Badshah", "Yo Yo Honey Singh"],
        ["Diljit Dosanjh", "Guru Randhawa"],
        ["Zakir Khan", "Biswa Kalyan Rath"],
        ["Samay Raina", "Munawar Faruqui"],
        ["Bhuvan Bam", "Ashish Chanchlani"],
        ["Technical Guruji", "Gaurav Chaudhary"],
        ["Dhruv Rathee", "Prashant Dhawan"],
        ["Sandeep Maheshwari", "Vivek Bindra"],
        ["Lata Mangeshkar", "Asha Bhosle"],
        ["Kishore Kumar", "Mohammed Rafi"],
        ["Irrfan Khan", "Om Puri"],
        ["Sushant Singh Rajput", "Ranveer Singh"],
        ["Radhika Apte", "Rasika Dugal"],
        ["Manoj Bajpayee", "Kay Kay Menon"],
        ["Sonakshi Sinha", "Parineeti Chopra"],
        ["Kriti Sanon", "Shraddha Kapoor"],
        ["Saif Ali Khan", "Shahid Kapoor"],
        ["Farhan Akhtar", "Ritesh Sidhwani"],
        ["Rajesh Khanna", "Dev Anand"],
        ["Dilip Kumar", "Raj Kapoor"],
    ],
    indianFood: [
        ["Biryani", "Pulao"],
        ["Dosa", "Uttapam"],
        ["Samosa", "Kachori"],
        ["Butter Chicken", "Chicken Tikka Masala"],
        ["Pani Puri", "Bhel Puri"],
        ["Chole Bhature", "Puri Sabzi"],
        ["Gulab Jamun", "Rasgulla"],
        ["Jalebi", "Imarti"],
        ["Paratha", "Naan"],
        ["Vada Pav", "Dabeli"],
        ["Idli", "Dhokla"],
        ["Pav Bhaji", "Misal Pav"],
        ["Rajma Chawal", "Dal Chawal"],
        ["Paneer Tikka", "Malai Chaap"],
        ["Chai", "Filter Coffee"],
        ["Kulfi", "Ice Cream"],
        ["Lassi", "Chaas"],
        ["Kheer", "Payasam"],
        ["Tandoori Chicken", "Afghani Chicken"],
        ["Masala Dosa", "Rava Dosa"],
        ["Momos", "Dim Sum"],
        ["Poha", "Upma"],
        ["Dal Makhani", "Dal Tadka"],
        ["Rasmalai", "Sandesh"],
        ["Kathi Roll", "Frankie"],
        ["Thali", "Buffet"],
        ["Maggi", "Yippee"],
        ["Panipuri", "Sev Puri"],
        ["Rabri", "Malpua"],
        ["Nihari", "Haleem"],
        ["Kebab", "Tikka"],
        ["Dum Aloo", "Jeera Aloo"],
        ["Gajar Halwa", "Moong Dal Halwa"],
        ["Raita", "Pachadi"],
        ["Chaat", "Dahi Bhalla"],
        ["Fish Curry", "Prawn Masala"],
        ["Rogan Josh", "Korma"],
        ["Mysore Pak", "Soan Papdi"],
        ["Pongal", "Khichdi"],
        ["Appam", "Hoppers"],
        ["Aam Ras", "Mango Shake"],
        ["Baingan Bharta", "Bharwan Baingan"],
        ["Kadhi Pakora", "Gujarati Kadhi"],
        ["Litti Chokha", "Dal Bati Churma"],
        ["Thandai", "Badam Milk"],
        ["Sambar", "Rasam"],
        ["Shrikhand", "Mishti Doi"],
        ["Kofta", "Meatball Curry"],
        ["Mathri", "Namak Pare"],
        ["Peda", "Barfi"],
    ],
    bollywoodSongs: [
        ["Chaiyya Chaiyya", "Dil Se Re"],
        ["Tujhe Dekha To", "Pehla Nasha"],
        ["Kal Ho Naa Ho", "Kabhi Alvida Naa Kehna"],
        ["Rang De Basanti", "Maa Tujhe Salaam"],
        ["Channa Mereya", "Ae Dil Hai Mushkil"],
        ["Tum Hi Ho", "Tera Ban Jaunga"],
        ["Kun Faya Kun", "Khwaja Mere Khwaja"],
        ["Gerua", "Suraj Hua Maddham"],
        ["Senorita", "Desi Girl"],
        ["London Thumakda", "Gallan Goodiyan"],
        ["Balam Pichkari", "Holi Ke Din"],
        ["Badtameez Dil", "Ghagra"],
        ["Jai Ho", "Ringa Ringa"],
        ["Kajra Re", "Kajra Mohabbat Wala"],
        ["Masakali", "Phir Le Aya Dil"],
        ["Zoobi Doobi", "Pappu Can't Dance"],
        ["Dil Dhadakne Do", "Gallan Goodiyan"],
        ["Lungi Dance", "Chennai Express"],
        ["Swag Se Swagat", "Zinda"],
        ["Mera Dil Bhi Kitna Pagal Hai", "Dil To Pagal Hai"],
        ["Tera Yaar Hoon Main", "Yaaron Dosti"],
        ["Apna Time Aayega", "Asli Hip Hop"],
        ["Aankhon Mein Teri", "Tere Bina"],
        ["Dil Ibadat", "Tujh Mein Rab Dikhta Hai"],
        ["Kesariya", "Ranjha"],
        ["Naatu Naatu", "Dholida"],
        ["Zingaat", "Khalibali"],
        ["Kar Gayi Chull", "High Heels"],
        ["Ghungroo", "Ek Toh Kum Zindagani"],
        ["Kala Chashma", "Saturday Saturday"],
        ["Aaj Ki Raat", "Sheila Ki Jawani"],
        ["Iktara", "Tum Se Hi"],
        ["Laree Choote", "Socha Hai"],
        ["Ilahi", "Patakha Guddi"],
        ["Galliyan", "Banjaara"],
        ["Ae Watan", "Teri Mitti"],
        ["Raabta", "Tere Sang Yaara"],
        ["Kabira", "Matargashti"],
        ["Manja", "Safarnama"],
        ["Abhi Mujh Mein Kahin", "Tera Fitoor"],
        ["Deva Shree Ganesha", "Ganpati Bappa Morya"],
        ["Maahi Ve", "Koi Mil Gaya"],
        ["Ainvayi Ainvayi", "Billo Rani"],
        ["Tumse Milke Dilka Jo Haal", "Papa Kehte Hain"],
        ["O Saathi Re", "Ek Pyaar Ka Nagma Hai"],
        ["Sapno Se Bhare Naina", "Naina"],
        ["Tere Liye", "Teri Ore"],
        ["Jashn-E-Bahaaraa", "Barso Re"],
        ["Mitwa", "Sajdaa"],
        ["Moh Moh Ke Dhaage", "Piya Tose Naina Laage Re"],
    ],
    cricket: [
        ["Helicopter Shot", "Reverse Sweep"],
        ["IPL", "World Cup"],
        ["Sachin Tendulkar", "Brian Lara"],
        ["Virat Kohli", "Steve Smith"],
        ["MS Dhoni", "Kumar Sangakkara"],
        ["Rohit Sharma", "David Warner"],
        ["Jasprit Bumrah", "Mitchell Starc"],
        ["Harbhajan Singh", "Anil Kumble"],
        ["Yuvraj 6 Sixes", "Herschelle Gibbs 6 Sixes"],
        ["2011 World Cup Final", "2007 T20 World Cup Final"],
        ["Gabba Test 2021", "Eden Gardens 2001"],
        ["Powerplay", "Death Overs"],
        ["Googly", "Doosra"],
        ["Yorker", "Bouncer"],
        ["DRS", "Third Umpire"],
        ["LBW", "Caught Behind"],
        ["Test Cricket", "ODI"],
        ["T20", "The Hundred"],
        ["Mumbai Indians", "Chennai Super Kings"],
        ["RCB", "Delhi Capitals"],
        ["KKR", "Rajasthan Royals"],
        ["Wankhede Stadium", "Eden Gardens"],
        ["Chinnaswamy", "Chepauk"],
        ["Inswing", "Outswing"],
        ["Cover Drive", "Square Cut"],
        ["Pull Shot", "Hook Shot"],
        ["Mankading", "Run Out"],
        ["Hat-trick", "Five-Wicket Haul"],
        ["Duckworth Lewis", "Super Over"],
        ["Night Watchman", "Pinch Hitter"],
        ["Sledging", "Spirit of Cricket"],
        ["Baggy Green", "Blue Jersey"],
        ["Ashes", "Border-Gavaskar Trophy"],
        ["Sachin's Desert Storm", "Kapil's 175"],
        ["Dhoni's Six 2011", "Joginder's Last Over 2007"],
        ["Shane Warne", "Muttiah Muralitharan"],
        ["Glenn McGrath", "Wasim Akram"],
        ["AB de Villiers", "Chris Gayle"],
        ["Rashid Khan", "Yuzvendra Chahal"],
        ["Bairstow", "Buttler"],
        ["Rahul Dravid", "VVS Laxman"],
        ["Sunil Gavaskar", "Kapil Dev"],
        ["Rishabh Pant", "Adam Gilchrist"],
        ["Caught and Bowled", "Stumped"],
        ["Maiden Over", "No Ball"],
        ["Free Hit", "Wide"],
        ["Orange Cap", "Purple Cap"],
        ["Toss", "Pitch Report"],
        ["Spin Bowling", "Fast Bowling"],
        ["Slip Fielding", "Boundary Catch"],
    ],
    hollywood: [
        ["Inception", "Interstellar"],
        ["The Dark Knight", "Batman Begins"],
        ["Avengers Endgame", "Infinity War"],
        ["Titanic", "The Notebook"],
        ["The Shawshank Redemption", "The Green Mile"],
        ["Fight Club", "American Psycho"],
        ["Forrest Gump", "The Pursuit of Happyness"],
        ["The Godfather", "Goodfellas"],
        ["Pulp Fiction", "Reservoir Dogs"],
        ["The Matrix", "Tron"],
        ["Jurassic Park", "King Kong"],
        ["Harry Potter", "Lord of the Rings"],
        ["Star Wars", "Star Trek"],
        ["Iron Man", "Batman"],
        ["Spider-Man", "Deadpool"],
        ["Joker", "Taxi Driver"],
        ["The Lion King", "Jungle Book"],
        ["Finding Nemo", "Finding Dory"],
        ["Toy Story", "Monsters Inc"],
        ["Frozen", "Tangled"],
        ["Fast and Furious", "Need for Speed"],
        ["John Wick", "The Equalizer"],
        ["Mission Impossible", "James Bond"],
        ["Die Hard", "Lethal Weapon"],
        ["The Hangover", "Superbad"],
        ["Home Alone", "Dennis the Menace"],
        ["Shutter Island", "Gone Girl"],
        ["The Prestige", "Now You See Me"],
        ["Gladiator", "Troy"],
        ["Saving Private Ryan", "Dunkirk"],
        ["The Wolf of Wall Street", "Catch Me If You Can"],
        ["Parasite", "Us"],
        ["Get Out", "Don't Breathe"],
        ["A Quiet Place", "Bird Box"],
        ["The Conjuring", "Insidious"],
        ["IT", "Stranger Things"],
        ["Rocky", "Creed"],
        ["Top Gun", "Top Gun Maverick"],
        ["Avatar", "Dune"],
        ["Oppenheimer", "A Beautiful Mind"],
        ["Bohemian Rhapsody", "Rocketman"],
        ["The Social Network", "Steve Jobs"],
        ["Jaws", "The Meg"],
        ["Alien", "Predator"],
        ["Terminator", "RoboCop"],
        ["Back to the Future", "Bill and Ted"],
        ["The Truman Show", "Free Guy"],
        ["Up", "Inside Out"],
        ["Coco", "Encanto"],
        ["Shrek", "Madagascar"],
    ],
    indianTV: [
        ["Sarabhai vs Sarabhai", "Khichdi"],
        ["Taarak Mehta Ka Ooltah Chashmah", "FIR"],
        ["CID", "Crime Patrol"],
        ["Sacred Games", "Mirzapur"],
        ["TVF Pitchers", "Kota Factory"],
        ["Panchayat", "Gullak"],
        ["Family Man", "Special Ops"],
        ["Scam 1992", "Rocket Boys"],
        ["Munna Bhai Circus", "Dekh Bhai Dekh"],
        ["Shaktimaan", "Hatim"],
        ["Kyunki Saas Bhi Kabhi Bahu Thi", "Kahani Ghar Ghar Ki"],
        ["Balika Vadhu", "Diya Aur Baati Hum"],
        ["Yeh Meri Family", "Flames"],
        ["Aspirants", "Kota Factory"],
        ["Kapil Sharma Show", "Comedy Nights with Kapil"],
        ["Bigg Boss", "Khatron Ke Khiladi"],
        ["KBC", "Jeeto Chappar Phaad Ke"],
        ["Indian Idol", "Sa Re Ga Ma Pa"],
        ["MTV Roadies", "Splitsvilla"],
        ["Naagin", "Sasural Simar Ka"],
        ["Ramayan", "Mahabharat"],
        ["Devon Ke Dev Mahadev", "Siya Ke Ram"],
        ["Byomkesh Bakshi", "Feluda"],
        ["Malgudi Days", "Jungle Book"],
        ["Shararat", "Son Pari"],
        ["Hip Hip Hurray", "Hum Paanch"],
        ["Office Office", "Yes Minister India"],
        ["Breathe", "Hostages"],
        ["Paatal Lok", "Delhi Crime"],
        ["Made in Heaven", "Four More Shots Please"],
        ["Asur", "Rudra"],
        ["Tandav", "Inside Edge"],
        ["Aarya", "Maharani"],
        ["Tu Tu Main Main", "Shrimaan Shrimati"],
        ["Flop Show", "Ulta Pulta"],
        ["Chanakya", "Upanishad Ganga"],
        ["Raja Rasoi Aur Anya Kahaniyaan", "Surabhi"],
        ["MTV Hustle", "Gully Boy"],
        ["Dance India Dance", "Jhalak Dikhhla Jaa"],
        ["Nach Baliye", "Super Dancer"],
        ["Kaun Banega Crorepati", "Dus Ka Dum"],
        ["Fear Factor India", "Survivor India"],
        ["Remix", "Dill Mill Gayye"],
        ["Jassi Jaisi Koi Nahin", "Ugly Betty"],
        ["Bade Achhe Lagte Hain", "Iss Pyaar Ko Kya Naam Doon"],
        ["Yeh Rishta Kya Kehlata Hai", "Anupamaa"],
        ["Ghum Hai Kisikey Pyaar Meiin", "Imlie"],
        ["Bandini", "Uttaran"],
        ["Laakhon Mein Ek", "College Romance"],
        ["Hostel Daze", "Engineering Girls"],
    ],
    dialogues: [
        ["Kitne aadmi the?", "Tera kya hoga Kaliya?"],
        ["Mogambo khush hua", "Crime Master Gogo"],
        ["Ja Simran ja, jee le apni zindagi", "Palat... palat..."],
        ["Don ko pakadna mushkil hi nahi, namumkin hai", "Rishte mein toh hum tumhare baap lagte hain"],
        ["Mere paas maa hai", "Aaj khush toh bahut hoge tum"],
        ["Babumoshai, zindagi badi honi chahiye lambi nahi", "Pushpa, I hate tears"],
        ["Ek baar jo maine commitment kar di", "Hum ek baar jeete hain, ek baar marte hain"],
        ["All izz well", "Life is a race"],
        ["Tumse na ho payega", "Jaa re jaa, jeele apni zindagi"],
        ["Picture abhi baaki hai mere dost", "Apna time aayega"],
        ["Utha le re baba", "Ae deva re deva"],
        ["Thappad se darr nahi lagta sahab", "Nahi dunga"],
        ["Sharma ji ka ladka", "Log kya kahenge"],
        ["Kuch toh log kahenge", "Izzat ka sawaal hai"],
        ["Hum jahan khade hote hain line wahi se shuru hoti hai", "Naam hai mera Shahenshah"],
        ["Main apni favourite hoon", "Main aisi kyun hoon"],
        ["Kabhi kabhi lagta hai apun hi bhagwan hai", "Apun ko toh bas ek hi cheez pasand hai"],
        ["Sara sheher mujhe lion ke naam se jaanta hai", "Yeh Baburao ka style hai"],
        ["Teja main hoon, mark idhar hai", "Aila, yeh toh Teja hai"],
        ["Dosti ka ek usool hai madam", "Tera dhyan kidhar hai"],
        ["How's the josh?", "Bharat mata ki jai"],
        ["Zindagi mein kuch banna ho toh apne baap ka naam suno", "Bade bade deshon mein aisi chhoti chhoti baatein"],
        ["Yeh dhai kilo ka haath", "Ek machhar aadmi ko hijda bana deta hai"],
        ["Tension lene ka nahi, dene ka", "Apun ka toh life jhand ho gaya"],
        ["Main aaj bhi phenke hue paise nahi uthata", "Yeh paisa nahi hai, meri maa ki duayein hain"],
        ["Bas kar pagle, rulaayega kya", "Pushpa, I hate tears"],
        ["Tarikh pe tarikh", "Insaaf ka mandir hai yeh"],
        ["Haar ke jeetne wale ko Baazigar kehte hain", "Kabhi kabhi jeetne ke liye kuch haarna bhi padta hai"],
        ["Entertainment ke liye kuch bhi karega", "Khamosh!"],
        ["Tumhara naam kya hai Basanti?", "Surangani..."],
        ["Aati kya Khandala?", "Koi mil gaya"],
        ["Itni shakti hame dena daata", "Aye mere watan ke logon"],
        ["Ye bik gayi hai gormint", "Bohot hard bohot hard"],
        ["Aam zindagi, khaas zindagi", "Thoda aur thoda aur"],
        ["With great power comes great responsibility", "I am inevitable"],
        ["Why so serious?", "I am Batman"],
        ["I'll be back", "Hasta la vista baby"],
        ["May the Force be with you", "Live long and prosper"],
        ["You talking to me?", "Say hello to my little friend"],
        ["Here's Johnny!", "Redrum"],
        ["I am Groot", "Avengers assemble"],
        ["To infinity and beyond", "Just keep swimming"],
        ["My precious", "You shall not pass"],
        ["I see dead people", "Here's looking at you kid"],
        ["Houston, we have a problem", "I'll make him an offer he can't refuse"],
        ["Keep your friends close, enemies closer", "Leave the gun, take the cannoli"],
        ["Yeh sab doglapan hai", "Ye kya ho raha hai"],
        ["Choti Bacchi Ho Kya", "Tera baap aaya"],
        ["Bilkul sahi pakde hain", "Ekdum se waqt badal diya"],
        ["Aur dikhao aur dikhao", "Ye lo ji, ye bhi thik hai"],
    ],
    indianObjects: [
        ["Chakki", "Silbatta"],
        ["Tawa", "Kadhai"],
        ["Cooker", "Handi"],
        ["Belan", "Chimta"],
        ["Jhaadu", "Pocha"],
        ["Matka", "Surahi"],
        ["Lota", "Balti"],
        ["Charpai", "Khatiya"],
        ["Diya", "Kandil"],
        ["Agarbatti", "Dhoop"],
        ["Bindi", "Sindoor"],
        ["Mangalsutra", "Payal"],
        ["Dupatta", "Chunni"],
        ["Kolhapuri Chappal", "Juttis"],
        ["Gamcha", "Lungi"],
        ["Tiffin Box", "Dabba"],
        ["Hawai Chappal", "Bata Shoes"],
        ["Auto Rickshaw", "Cycle Rickshaw"],
        ["Jugaad", "Desi Hack"],
        ["Transistor Radio", "Murphy Radio"],
        ["Ambassador Car", "Maruti 800"],
        ["Ceiling Fan", "Table Fan"],
        ["Desert Cooler", "AC"],
        ["Washing Stone", "Washboard"],
        ["Steel Ka Dabba", "Masala Box"],
        ["Pankha", "Hand Fan"],
        ["Tulsi Ka Gamla", "Money Plant"],
        ["Atta Chakki", "Mixer Grinder"],
        ["Sewing Machine", "Spinning Wheel"],
        ["Chulha", "Gas Stove"],
        ["Lantern", "Torchlight"],
        ["Thela", "Rehdi"],
        ["Dhol", "Tabla"],
        ["Harmonium", "Tanpura"],
        ["Sitar", "Veena"],
        ["Bansuri", "Shehnai"],
        ["Rangoli", "Alpona"],
        ["Kalash", "Lota"],
        ["Toran", "Bandhanwar"],
        ["Jhula", "Palki"],
        ["Howdah", "Bullock Cart"],
        ["Chakra", "Trishul"],
        ["Rudraksha", "Tulsi Mala"],
        ["Puja Thali", "Aarti Ki Thali"],
        ["Kamandal", "Jholi"],
        ["Hookah", "Chillum"],
        ["Supari", "Paan"],
        ["Muddha", "Mora"],
        ["Tokri", "Chhalni"],
        ["Ghanti", "Shankhnaad"],
    ],
};

// Get words for a category (or all mixed)
function getWordPair(category) {
    let pool;
    if (category === 'all') {
        pool = [
            ...WORDS.bollywood, ...WORDS.memes, ...WORDS.celebrities,
            ...WORDS.indianFood, ...WORDS.bollywoodSongs, ...WORDS.cricket,
            ...WORDS.hollywood, ...WORDS.indianTV, ...WORDS.dialogues,
            ...WORDS.indianObjects
        ];
    } else {
        pool = WORDS[category];
    }
    const index = Math.floor(Math.random() * pool.length);
    return pool[index];
}
